version: '3.3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: simple-mvc
    restart: always
    working_dir: /var/www/html
    volumes:
      - ../src:/var/www/html
    ports:
      - "8080:80"

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"
